<?php 
$_productCollection = $this->getProductlistinCurrentCategory();
?>

<?php foreach ($_productCollection as $_product): ?>
<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getSmallImageLabel()) ?>">
                 <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(172, 172); ?>" width="172" height="172" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
 </a>
 <?php endforeach; ?>