<?php 
$_productCollection = $this->getProductlistinCurrentCategory();
?>
<?php if($_productCollection!= null):?>
<div>

<script type="text/javascript">

jQuery(document).ready(function() {
    jQuery('#scroller').jcarousel();
});

</script>

<ul id="scroller" class="jcarousel-skin-tango">
<!-- List all pics here -->
<?php foreach ($_productCollection as $_product): ?>
<li>
<div class="jcarousel-inner-div">
<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getSmallImageLabel())?>">
<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image'); ?>" width="160" height="120" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" title="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image')) ?>" />
</a>
<div class="jcarousel-inner-div-title"><span><?php echo $_product->getName();?></span></div>
</div>
</li>
<?php endforeach; ?>
</ul>
</div>
<?php endif;?>