
<div style="width:400px;" id="AdPromotion">
<?php
        $quilts = Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(21);
        $bedlinen =  Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(48);
        $quiltCovers =  Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(4);
        $winterSpecial= Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(5);
        $pillows =   Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(22);
        $cushions =   Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(24);
?>

<?php if($this->overThresholdBedlinen() && $this->containsBedlinen() && !$this->containsGiftCushion()):?>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Advertisements - Congrats - BEDLINEN.jpg"  id="congratBedlinen"/>
<?php
    /*$category = Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(34);
    Mage::register('current_category', $category);*/

    Mage::getSingleton('catalog/layer')->setCurrentCategory(34);
    echo $this->getChildHtml('giftListBedlinen');
    $showGiftListBedlinen=true;
?>
<div style="height:25px;width:400px;"></div>
<?php endif;?>
<?php
if($this->overThresholdQuilt() && $this->containsQuilt() && !$this->containsGiftPillow()):?>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Advertisements - Congrats - QUILTS.jpg"  id="congratQuilt"/>
<?php
   /* $category = Mage::getModel('catalog/category')
            ->setStoreId(Mage::app()->getStore()->getId())
            ->load(35);
    Mage::register('current_category', $category);
*/
    Mage::getSingleton('catalog/layer')->setCurrentCategory(35);
    echo $this->getChildHtml('giftListQuilt');
    $showGiftListQuilt=true;
?>
<div style="height:25px;width:400px;"></div>
<?php endif;?>

<?php if($this->containsBedlinen() && $this->containsQuilt() && !$this->overThresholdQuilt() && !$this->overThresholdBedlinen()):?>
<?php $promBoth=true ?>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Both1.jpg"  id="AdBoth1"/>
<a href=<?php echo $url = $quiltCovers->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Both_bedlinen.jpg" id="AdBothBedlinen"/>
</a>
<a href=<?php echo $url = $quilts->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Both_quilts.jpg" id="AdBothQuilts"/>
</a>
<?php elseif($this->containsQuilt() && !$this->overThresholdQuilt()):?>
<?php $promQuilt=true ?>
<a href=<?php echo $url = $quilts->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Quilts.jpg" id="AdFreePillow"/>
</a>

<?php elseif($this->containsBedlinen() && !$this->overThresholdBedlinen()):?>
<?php $promBedlinen=true ?>
<a href=<?php echo $url = $quiltCovers->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Bedlinen.jpg" id="AdFreeCushion"/>
</a>

<?php elseif(!$this->containsBedlinen() && !$this->containsQuilt()):?>
<?php $promBoth2=true ?>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Both1.jpg"  id="AdDefault1"/>
<a href=<?php echo $url = $quiltCovers->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Both_bedlinen.jpg" id="AdDefaultBedlinen"/>
</a>
<a href=<?php echo $url = $quilts->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_Both_quilts.jpg" id="AdDefaultQuilts"/>
</a>
<?php endif;?>
<?php if(!$showGiftListQuilt && !$showGiftListBedlinen && !$promBoth && !$promQuilt && !$promBedlinen && !$promBoth2 ):?>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Promotion_General.jpg" id="AdDefaultGeneral"/>
<div style="height:25px;width:400px;"></div>
<?php endif;?>
</div>
<div style="height:20px;width:400px;"></div>
<a href=<?php echo $url = $winterSpecial->getUrl();?>>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Winter Specials.jpg" id="Thin"/>
</a>
<div style="height:10px;width:400px;"></div>
<img src="<?php echo $this->getSkinUrl();?>images/gains/Secure Shopping.jpg" id="secureshop"/>
<div style="height:10px;width:400px;"></div>
