<div class="slideshow" style="position: relative; left: 0; top: 0;">
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery1.jpg" width="906" height="408" style="position: relative; top: 0; left: 0; z-index:1"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery2.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery3.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery4.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery5.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery6.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery7.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
<img src="<?php echo $this->getSkinUrl()?>/images/SlideShow/GB-jquery8.jpg" width="906" height="408"  style="position: absolute;  top:0; left:0;"/>
</div>
